before_install:
  rvm install 2.2.2
language: ruby
rvm:
- 2.2.2
bundler_args: --without production

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake

after_script:
  - bundle exec rake send_to_codeclimate

addons:
  code_climate:
    repo_token: f048e9b7147365e2d4d864acbca2e2820d218432cd4c741b9592f43512ac5b43
